# Generated by Django 3.1.3 on 2021-04-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learning_type',
            field=models.CharField(choices=[('0', 'Wzrokowiec'), ('1', 'Kinestetyk'), ('2', 'Słuchowiec')], default='0', max_length=30),
        ),
    ]
