# Generated by Django 3.1.3 on 2021-03-27 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('0', 'Wzrokowiec'), ('1', 'Dzidowiec'), ('2', 'Słuchowiec')], default='0', max_length=10)),
                ('lesson_file', models.FileField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('node_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.node')),
                ('files', models.ManyToManyField(blank=True, related_name='learning_files', to='courses.LessonFile')),
            ],
            bases=('courses.node',),
        ),
        migrations.CreateModel(
            name='LessonInCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_course', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_in_course', to='courses.lesson')),
            ],
            options={
                'ordering': ('lesson_number',),
                'unique_together': {('course', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(through='courses.LessonInCourse', to='courses.Lesson'),
        ),
    ]
