# Generated by Django 3.1.3 on 2021-03-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_number', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('node_number',),
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.DeleteModel(
            name='LessonInCourse',
        ),
        migrations.AddField(
            model_name='nodeincourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='nodeincourse',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_in_course', to='courses.node'),
        ),
        migrations.AddField(
            model_name='course',
            name='nodes',
            field=models.ManyToManyField(through='courses.NodeInCourse', to='courses.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeincourse',
            unique_together={('course', 'node')},
        ),
    ]
