# Generated by Django 3.1.3 on 2021-05-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='node_count',
        ),
    ]
