# Generated by Django 3.1.3 on 2021-04-21 21:09

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson_file',
            field=models.FileField(upload_to=courses.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson_type',
            field=models.CharField(choices=[('0', 'Wzrokowiec'), ('1', 'Kinestetyk'), ('2', 'Słuchowiec')], default='0', max_length=20),
        ),
    ]
