# Generated by Django 3.1.3 on 2021-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210421_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson_type',
            field=models.CharField(choices=[(0, 'Wzrokowiec'), (1, 'Kinestetyk'), (2, 'Słuchowiec')], default='0', max_length=20),
        ),
    ]
