# Generated by Django 3.1.3 on 2021-03-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210327_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_number',
        ),
    ]
