# Generated by Django 3.1.3 on 2021-03-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_node_node_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=200, null=True)),
                ('answers', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(blank=True, choices=[('lesson', 'Lekcja'), ('test', 'Test')], max_length=20),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.node')),
                ('questions', models.ManyToManyField(to='courses.Question')),
            ],
            bases=('courses.node',),
        ),
    ]
