# Generated by Django 3.1.3 on 2021-05-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210525_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(default=(), to='courses.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='Pytanie', max_length=200),
        ),
    ]
