# Generated by Django 3.1.3 on 2021-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210328_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('lesson', 'Lekcja'), ('test', 'Test')], default='lesson', max_length=20),
        ),
    ]
