# Generated by Django 3.1.3 on 2021-04-22 09:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210422_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Wzrokowiec'), ('1', 'Kinestetyk'), ('2', 'Słuchowiec')], max_length=5),
        ),
    ]
