# Generated by Django 3.1.3 on 2021-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210328_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
