# Generated by Django 3.1.3 on 2021-04-22 11:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210422_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='content',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Wzrokowiec'), ('1', 'Kinestetyk'), ('2', 'Słuchowiec')], default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='node',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
