# Generated by Django 3.1.3 on 2021-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210328_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='courses.Question'),
        ),
    ]
