# Generated by Django 3.1.3 on 2021-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210328_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfile',
            name='lesson_file',
            field=models.FileField(blank=True, upload_to='upload/'),
        ),
    ]
